const products = [
{catégorie: 'Applique',
name: 'Applique s',
longueur : "25 cm",
largeur : "25 cm" ,
profondeur : "8,5 cm",
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/1.jpg',
price: '50 Dinars'},
{catégorie: 'Lustre',
name: "LUSTRE CER",
hauteur : "30 cm",
D : "20 cm",
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/5.jpg',
price: '40 Dinars',},
{Catégorie: "Lustre",
name: "Lustre DAM",
hauteur: "44 cm",
largeur : "33 cm",
profondeur : "26 cm",
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/telechargement.jpg',
price: '38 Dinars'},
{Catégorie: "Lustre",
name: "Lustre en MDF avec motif personnalisable",
hauteur : "33 cm",
largeur : "17 cm",
profondeur : "20 cm",
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/6-1.jpg',
price:'45 Dinars'},
{catégorie: "Porte Bijoux",
name: 'PORTE BIJOUX ARBRE',
description: 'Porte Bijoux Arbre en MDF',
hauteur: '25 cm',
largeur: '15 cm',
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/WhatsApp-Image-2022-12-27-at-09.31.30.jpeg',
price: '20 Dinars'},
{catégorie: 'Porte Bijoux',
name: 'PORTE BIJOUX CHAT',
description: 'Porte Bijoux chat en MDF',
hauteur: '27 cm',
largeur: '28 cm',
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/WhatsApp-Image-2022-12-27-at-09.32.13.jpeg',
price: '23 Dinars'},
{catégorie: 'Porte Carte',
name: 'Porte Carte',
description: 'Porte Carte en cuir de vachette',
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/Porte-carte-scaled.jpg',
price: '15 Dinars',
},
{catégorie: 'Porte Passeport',
name: 'PORTE PASSEPORT',
description: 'Porte Passeport avec possibilité de personnalisation. La couture de ce produit est fait main ce qui augmente sa valeur.',
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/Porte-passeport-scaled.jpg',
price: '40 Dinars'},
{catégorie: 'Sac à main',
name: 'SAC À MAIN',
description: 'Sac à main en Cuir de vachette pour femme de haute qualité avec une couture fait main.',
image: 'https://3d-creativity.com/wp-content/uploads/2023/01/Sac-a-main-cuir-scaled.jpg',
price: '170 Dinars'}
]
export default products;